using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AIO.Data.Migrations
{
    public partial class AutoGeneratedAndSeed : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Name" },
                values: new object[] { 1, "Vehicle" });

            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Name" },
                values: new object[] { 2, "Bicycle" });

            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Name" },
                values: new object[] { 3, "Real Estate" });

            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "Id", "AgentId", "BuyerId", "CategoryId", "CurrentBid", "Description", "EndTime", "ImageUrl", "IsAuctionClosed", "OpeningBid", "StartTime", "Title" },
                values: new object[] { new Guid("2a94b425-27ce-4762-955a-c10ecc3c99d1"), new Guid("db47b449-630e-4857-bc80-34a6c3e8e822"), new Guid("ab6d096a-0ccc-49ae-2db2-08dc32d4f58a"), 2, 120m, "A bike for sale", new DateTime(2024, 2, 28, 12, 45, 59, 523, DateTimeKind.Utc).AddTicks(6005), "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", false, 100m, new DateTime(2024, 2, 21, 12, 45, 59, 523, DateTimeKind.Utc).AddTicks(6004), "Bike" });

            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "Id", "AgentId", "BuyerId", "CategoryId", "CurrentBid", "Description", "EndTime", "ImageUrl", "IsAuctionClosed", "OpeningBid", "StartTime", "Title" },
                values: new object[] { new Guid("5cd1ee0c-fb36-46a8-812e-d8afb6fe7a05"), new Guid("db47b449-630e-4857-bc80-34a6c3e8e822"), new Guid("ab6d096a-0ccc-49ae-2db2-08dc32d4f58a"), 1, 12000m, "A car for sale", new DateTime(2024, 2, 28, 12, 45, 59, 523, DateTimeKind.Utc).AddTicks(5944), "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGNhcnN8ZW58MHx8MHx8fDA%3D", false, 10000m, new DateTime(2024, 2, 21, 12, 45, 59, 523, DateTimeKind.Utc).AddTicks(5939), "Car" });

            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "Id", "AgentId", "BuyerId", "CategoryId", "CurrentBid", "Description", "EndTime", "ImageUrl", "IsAuctionClosed", "OpeningBid", "StartTime", "Title" },
                values: new object[] { new Guid("9ec851e5-edf6-4a97-bc2d-030773be9646"), new Guid("db47b449-630e-4857-bc80-34a6c3e8e822"), null, 3, 120000m, "A house for sale", new DateTime(2024, 2, 28, 12, 45, 59, 523, DateTimeKind.Utc).AddTicks(6017), "https://www.bhg.com/thmb/H9VV9JNnKl-H1faFXnPlQfNprYw=/1799x0/filters:no_upscale():strip_icc()/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg", false, 100000m, new DateTime(2024, 2, 21, 12, 45, 59, 523, DateTimeKind.Utc).AddTicks(6017), "House" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Products",
                keyColumn: "Id",
                keyValue: new Guid("2a94b425-27ce-4762-955a-c10ecc3c99d1"));

            migrationBuilder.DeleteData(
                table: "Products",
                keyColumn: "Id",
                keyValue: new Guid("5cd1ee0c-fb36-46a8-812e-d8afb6fe7a05"));

            migrationBuilder.DeleteData(
                table: "Products",
                keyColumn: "Id",
                keyValue: new Guid("9ec851e5-edf6-4a97-bc2d-030773be9646"));

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 3);
        }
    }
}
